name: Python application

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Setup test environment
      run: |
        docker run -d --rm -e POSTGRES_PASSWORD=mysecretpassword -p 5432:5432 --name postgres postgres
        sleep 15
        docker exec -u postgres postgres psql -c "create database test_db;"
        docker exec -u postgres postgres psql -c "create role u1 password '1'"
        docker exec -u postgres postgres psql -c "alter role u1 login superuser"
    - name: Test with pytest
      run: |
        pytest